# ใช้ Node.js เวอร์ชัน LTS
FROM node:22-alpine

# ตั้งค่า Working Directory
WORKDIR /app

# คัดลอก package.json และติดตั้ง dependencies
COPY package.json package-lock.json ./
RUN npm install -f

# คัดลอกโค้ดทั้งหมด
COPY . .

# เปิดพอร์ต 3000
# EXPOSE 3000

# ใช้โหมด dev
CMD ["npm", "run", "dev"]
