import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import { ToastContainer } from "react-toastify";
import Header from "@/components/Header";
import SideMenu from "@/components/SideMenu";
import InfoTask from "@/components/InfoTask";

const inter = Inter({ subsets: ["latin"], weight: "400" });
const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} antialiased`}>
        <ToastContainer position="top-center" theme="light" />

        <QueryProvider>
          <Header />
          <main className="flex justify-between min-h-screen">
            <SideMenu />
            {children}
            <InfoTask />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
